### ISSUE TITLE
生成aar调用无声音

### ISSUE THREAD

**Issue by watersoft123** [cczhr/voice-tts#4]
我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！

**Comment by cczhr** [comment]
> 我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！

打包后aar不包含so库的 要外部引用

**Comment by cczhr** [comment]
> 我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！
“是不是还有其它的依赖”  
没有了

**Comment by watersoft123** [comment]
> > 我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！
> > “是不是还有其它的依赖”
> > 没有了

谢谢，最后一位大佬帮我找到了问题，B4X不能获取assets子文件夹里面的mp3声音模型。

**Comment by watersoft123** [comment]
> > 我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！
> > “是不是还有其它的依赖”
> > 没有了
还有一个问题想问下，在安卓原生TTS里面有一个isSpeaking的布尔值，可以判断播放状态。那吗在讯飞这个里面对应是哪个？

**Comment by cczhr** [comment]
> > > 我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！
> > > “是不是还有其它的依赖”
> > > 没有了
> > > 还有一个问题想问下，在安卓原生TTS里面有一个isSpeaking的布尔值，可以判断播放状态。那吗在讯飞这个里面对应是哪个？


我加上去了 用最新的代码就有了 tts.isSpeaking();

**Comment by watersoft123** [comment]
> > > > 我想在第三方开发工具B4X中使用，我先在AS中生成aar，也包含了so库，在B4X中调用aar没有错误，然而却发不出声音，我想知道是不是还有其它的依赖？谢谢！
> > > > “是不是还有其它的依赖”
> > > > 没有了
> > > > 还有一个问题想问下，在安卓原生TTS里面有一个isSpeaking的布尔值，可以判断播放状态。那吗在讯飞这个里面对应是哪个？
> 
> 我加上去了 用最新的代码就有了 tts.isSpeaking();

试了下，不错，谢谢
