### ISSUE TITLE
同一个设备，使用您的demo语速和语调正常，然后我新建一个demo,语速变得很快并且设置语速和语调没用，这个是什么原因呢

### ISSUE THREAD

**Issue by 765817054** [cczhr/voice-tts#7]

**Comment by cczhr** [comment]
看下代码

**Comment by 765817054** [comment]
`public class MainActivity extends AppCompatActivity {

    private TTS tts;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        tts = TTS.getInstance();
        tts.init(this);
        findViewById(R.id.btn_play).setOnClickListener(view -> {
            tts.speakText("测试播放");
        });
    }

    public void stop(View view) {
        tts.stop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        tts.release();
    }
}`

**Comment by 765817054** [comment]
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tyb.testdemo'
    compileSdkVersion 31
    buildToolsVersion "30.0.3"
    defaultConfig {
        applicationId "com.tyb.testdemo"
        minSdk 19
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi'//'armeabi-v7a-v8a' //'armeabi' //, 'x86', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: [".jar", ".aar"])
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.github.cczhr:voice-tts:1.0.1'
}

**Comment by 765817054** [comment]
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "TestDemo"
include ':app'
//include ':tts'

**Comment by cczhr** [comment]
[TTSDemo.zip](https://github.com/cczhr/voice-tts/files/11999745/TTSDemo.zip)
我自己写了个demo也是正常喔 不太清楚什么问题

**Comment by 765817054** [comment]
我您的demo也是一样的问题，那估计是设备问题，谢谢解答
