### ISSUE TITLE
anddroid7.1.2上语速变快，音调变高。

### ISSUE THREAD

**Issue by Morita9615** [cczhr/voice-tts#8]
您好：
      您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成的您的机器基本两秒就播放完成了。

**Comment by cczhr** [comment]
> 您好： 您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成的您的机器基本两秒就播放完成了。
有试过同系统版本不同型号的设备么，手头上没这个系统版本的设备测试，好像和机型有关系。

**Comment by cczhr** [comment]
> 您好： 您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成的您的机器基本两秒就播放完成了。


有试过同系统版本不同型号的设备么，手头上没这个系统版本的设备测试，好像和机型有关系。

**Comment by cczhr** [comment]
> 您好： 您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成的您的机器基本两秒就播放完成了。

可以用这个demo试试
[TTSDemo.zip](https://github.com/cczhr/voice-tts/files/12557911/TTSDemo.zip)

**Comment by cczhr** [comment]
也可以针对设备调下音速音调
![image](https://github.com/cczhr/voice-tts/assets/20502238/1a8526ba-df83-4725-abcb-6d849a981e80)

**Comment by Klosw** [comment]
我也遇到了 ,垃圾设备 操

**Comment by Klosw** [comment]
> 您好： 您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成您的机器基本两秒就播放完成。

我也有相同的问题,测试过了 语音合成没有问题 ,是播放设置存在问题  
![image](https://github.com/cczhr/voice-tts/assets/13143959/bbb00e9d-cf6b-42d7-a67a-1e0d1b197867)

**Comment by Klosw** [comment]
> 您好： 您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成您的机器基本两秒就播放完成。
修改TTS  audioTrack 创建的是修改为单通道 就正常了 
![image](https://github.com/cczhr/voice-tts/assets/13143959/f1d9ff73-e1ea-4c88-b157-b21bd8536a45)

**Comment by cczhr** [comment]
> > 您好： 您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成您的机器基本两秒就播放完成。
> > 修改TTS  audioTrack 创建的是修改为单通道 就正常了
> > ![image](https://user-images.githubusercontent.com/13143959/269150973-f1d9ff73-e1ea-4c88-b157-b21bd8536a45.png)

好的 感谢感谢~ 我这边也更新下

**Comment by Klosw** [comment]
> > > 您好：您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成您的机器基本两秒就播放完成。修改TTS audioTrack创建是将修改为单通道就正常
> > > 了
> > > ![图像](https://user-images.githubusercontent.com/13143959/269150973-f1d9ff73-e1ea-4c88-b157-b21bd8536a45.png)
> 
> 好的谢谢谢谢~我的坚果也更新下

你试一试 看看别的机器会不会存在问题

**Comment by Klosw** [comment]
我擦 ,别的设备TM 变慢了

**Comment by cczhr** [comment]
> > > > 您好：您的包在7.1.2上面语速和音调都会变高，正常其他机器5秒播放完成您的机器基本两秒就播放完成。修改TTS audioTrack创建是将修改为单通道就正常
> > > > 了
> > > > ![图像](https://user-images.githubusercontent.com/13143959/269150973-f1d9ff73-e1ea-4c88-b157-b21bd8536a45.png)
> > 
> > 
> > 好的谢谢谢谢~我的坚果也更新下
> 
> 你试一试 看看别的机器会不会存在问题

我这边都是CHANNEL_OUT_STEREO正常的设备，改成CHANNEL_OUT_MONO会音速变慢音调变低

**Comment by Klosw** [comment]
是呀 就只能针对 个别的设备 这样设置  ..

**Comment by cczhr** [comment]
> 是呀 就只能针对 个别的设备 这样设置 ..
把audioTrack.setPlaybackRate(tone); 注释试试，我这边用CHANNEL_OUT_MONO正常了，看看你那边的设备
![image](https://github.com/cczhr/voice-tts/assets/20502238/8bee75a4-7491-4374-8694-adf40b5c3c00)

**Comment by cczhr** [comment]
![image](https://github.com/cczhr/voice-tts/assets/20502238/c6c96f53-2733-46d0-af4d-4e1cfb273aef)
或者把默认 tone改成16000，应该就是tone这个问题吧

**Comment by Klosw** [comment]
这个 tone 修改过了  没啥效果  

> > 是呀 就只能针对 个别的设备 这样设置 ..
> > 把audioTrack.setPlaybackRate(tone); 注释试试，我这边用CHANNEL_OUT_MONO正常了，看看你那边的设备
> > ![image](https://user-images.githubusercontent.com/20502238/269162692-8bee75a4-7491-4374-8694-adf40b5c3c00.png)
你这个位置我试过了 不行  tone  改大 改小 也不行  效果也不好

**Comment by cczhr** [comment]
> 这个 tone 修改过了 没啥效果
> 
> > > 是呀 就只能针对 个别的设备 这样设置 ..
> > > 把audioTrack.setPlaybackRate(tone); 注释试试，我这边用CHANNEL_OUT_MONO正常了，看看你那边的设备
> > > ![image](https://user-images.githubusercontent.com/20502238/269162692-8bee75a4-7491-4374-8694-adf40b5c3c00.png)
> > > 你这个位置我试过了 不行  tone  改大 改小 也不行  效果也不好

好吧😥

**Comment by Klosw** [comment]
调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题  ,后来发现不是  ,才想到修改声道 来测试的

**Comment by cczhr** [comment]
> 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
```
new AudioTrack(AudioManager.STREAM_MUSIC,
                    16000,
                    2, AudioFormat.ENCODING_PCM_16BIT,
                    AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
                    , AudioTrack.MODE_STREAM);
```

**Comment by cczhr** [comment]
然后去掉变调
```
    @Override
    public int audioAvailable(byte[] buffer, int offset, int length) {
      //  audioTrack.setPlaybackRate(tone);
        audioTrack.write(buffer, offset, length);
        return 0;
    }
```

**Comment by Klosw** [comment]
> > 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
> > 用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
> 
> ```
> new AudioTrack(AudioManager.STREAM_MUSIC,
>                     16000,
>                     2, AudioFormat.ENCODING_PCM_16BIT,
>                     AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
>                     , AudioTrack.MODE_STREAM);
> ```
这个CHANNEL_CONFIGURATION_MONO 在变快的设备 是可以正常的

**Comment by cczhr** [comment]
> > > 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
> > > 用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
> > 
> > 
> > ```
> > new AudioTrack(AudioManager.STREAM_MUSIC,
> >                     16000,
> >                     2, AudioFormat.ENCODING_PCM_16BIT,
> >                     AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
> >                     , AudioTrack.MODE_STREAM);
> > ```
> 
> 这个CHANNEL_CONFIGURATION_MONO 在变快的设备 是可以正常的

那应该就是这个问题了，我这边原本没快的也正常，你看看你那边其它设备是不是也一样正常。都ok的话我更新下

**Comment by Klosw** [comment]
> > > > 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
> > > > 用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
> > > 
> > > 
> > > ```
> > > new AudioTrack(AudioManager.STREAM_MUSIC,
> > >                     16000,
> > >                     2, AudioFormat.ENCODING_PCM_16BIT,
> > >                     AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
> > >                     , AudioTrack.MODE_STREAM);
> > > ```
> > 
> > 
> > 这个CHANNEL_CONFIGURATION_MONO 在变快的设备 是可以正常的
> 
> 那应该就是这个问题了，我这边原本没快的也正常，你看看你那边其它设备是不是也一样正常。都ok的话我更新下
我这边 没快的变慢了

**Comment by cczhr** [comment]
> > > > > 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
> > > > > 用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
> > > > 
> > > > 
> > > > ```
> > > > new AudioTrack(AudioManager.STREAM_MUSIC,
> > > >                     16000,
> > > >                     2, AudioFormat.ENCODING_PCM_16BIT,
> > > >                     AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
> > > >                     , AudioTrack.MODE_STREAM);
> > > > ```
> > > 
> > > 
> > > 这个CHANNEL_CONFIGURATION_MONO 在变快的设备 是可以正常的
> > 
> > 
> > 那应该就是这个问题了，我这边原本没快的也正常，你看看你那边其它设备是不是也一样正常。都ok的话我更新下
> > 我这边 没快的变慢了
这行代码去掉试试
···
audioTrack.setPlaybackRate(tone);
···

**Comment by Klosw** [comment]
> > > > > > 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
> > > > > > 用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
> > > > > 
> > > > > 
> > > > > ```
> > > > > new AudioTrack(AudioManager.STREAM_MUSIC,
> > > > >                     16000,
> > > > >                     2, AudioFormat.ENCODING_PCM_16BIT,
> > > > >                     AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
> > > > >                     , AudioTrack.MODE_STREAM);
> > > > > ```
> > > > 
> > > > 
> > > > 这个CHANNEL_CONFIGURATION_MONO 在变快的设备 是可以正常的
> > > 
> > > 
> > > 那应该就是这个问题了，我这边原本没快的也正常，你看看你那边其它设备是不是也一样正常。都ok的话我更新下
> > > 我这边 没快的变慢了
> > > 这行代码去掉试试
> > > ···
> > > audioTrack.setPlaybackRate(tone);
> > > ···

去掉这个 就OK 了,我再试一试 那个设备

**Comment by Klosw** [comment]
> > > > > > 调了好久 好久 我都把音频数据拿出来 了 ,我刚开始是以为是 音频数据 转出来就有问题 ,后来发现不是 ,才想到修改声道 来测试的
> > > > > > 用这个再试试  2 是老版本的单声道CHANNEL_CONFIGURATION_MONO 我这边也是正常的，你看看原本快的设备可不可以
> > > > > 
> > > > > 
> > > > > ```
> > > > > new AudioTrack(AudioManager.STREAM_MUSIC,
> > > > >                     16000,
> > > > >                     2, AudioFormat.ENCODING_PCM_16BIT,
> > > > >                     AudioTrack.getMinBufferSize(16000, 2, AudioFormat.ENCODING_PCM_16BIT)*2
> > > > >                     , AudioTrack.MODE_STREAM);
> > > > > ```
> > > > 
> > > > 
> > > > 这个CHANNEL_CONFIGURATION_MONO 在变快的设备 是可以正常的
> > > 
> > > 
> > > 那应该就是这个问题了，我这边原本没快的也正常，你看看你那边其它设备是不是也一样正常。都ok的话我更新下
> > > 我这边 没快的变慢了
> > > 这行代码去掉试试
> > > ···
> > > audioTrack.setPlaybackRate(tone);
> > > ···
去掉后  变快的设备也好了  , 其他设备也好了

**Comment by cczhr** [comment]
好的 谢谢测试😀 我更新下

**Comment by Klosw** [comment]
> 好的 谢谢测试😀 我更新下

改变音调 可以在合成的时候 修改 呀 就是 你修改语速后面那个参数

**Comment by Klosw** [comment]
这个方法修改 成这个可以无极调速  
![image](https://github.com/cczhr/voice-tts/assets/13143959/9ead7c81-e153-48e4-9025-a3f3c44ab6b3)

**Comment by Klosw** [comment]
![image](https://github.com/cczhr/voice-tts/assets/13143959/dec56805-ca79-4add-9e36-655e568cacd7)

**Comment by cczhr** [comment]
> ![image](https://user-images.githubusercontent.com/13143959/269536678-dec56805-ca79-4add-9e36-655e568cacd7.png)

哇原来如此，一直没发现 。

**Comment by Klosw** [comment]
> > ![image](https://user-images.githubusercontent.com/13143959/269536678-dec56805-ca79-4add-9e36-655e568cacd7.png)
> 
> 哇原来如此，一直没发现 。
后面那个参数是音量   一般是应该参数和 语速语调应该是一样的  应该 没啥用   ,我也没去实现 ...

**Comment by Klosw** [comment]
> 这个方法修改 成这个可以无极调速 ![image](https://user-images.githubusercontent.com/13143959/269536510-9ead7c81-e153-48e4-9025-a3f3c44ab6b3.png)
改了这个 默认值就是  50 了 不能是 100 了

**Comment by cczhr** [comment]
```
    private static final int ivTTS_PARAM_MAX = 32767;
 public static int convertToLocalParam(int value) {
        if (value < 0 || value > 100) {
            return 0;
        }
        return ((value - 50) * ivTTS_PARAM_MAX) / 50;
    }

.....
convertToLocalParam(pitch)
```

> > 这个方法修改 成这个可以无极调速 ![image](https://user-images.githubusercontent.com/13143959/269536510-9ead7c81-e153-48e4-9025-a3f3c44ab6b3.png)
> > 改了这个 默认值就是  50 了 不能是 100 了

用这个 0-100

**Comment by cczhr** [comment]
50 是默认值

**Comment by Klosw** [comment]
> 50 是默认值
已修改 

![image](https://github.com/cczhr/voice-tts/assets/13143959/a25baf7d-fb59-4974-aa75-136a9be46875)

**Comment by cczhr** [comment]
已更新到1.0.2
