### ISSUE TITLE
日志输出问题

### ISSUE THREAD

**Issue by yyfd2013zy** [cczhr/voice-tts#9]
非常感谢您开源此项目, 使用过程中发现有大量tag为TTS_Aitalk5_jni的日志输出，请问这部分日志有办法关掉么
如下
![jinlog](https://github.com/cczhr/voice-tts/assets/21209643/adbb0bd8-db85-47be-9d42-377f7a3d34b7)

**Comment by cczhr** [comment]
> 非常感谢您开源此项目, 使用过程中发现有大量tag为TTS_Aitalk5_jni的日志输出，请问这部分日志有办法关掉么 如下

关不了
